export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_QUANTITY_CART = 'INCREMENT_QUANTITY_CART';
export const DECREMENT_QUANTITY_CART = 'DECREMENT_QUANTITY_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SUB_TOTAL = 'SUB_TOTAL';
export const UPDATE_STORAGE_CART = 'UPDATE_STORAGE_CART';
export const CLEAN_CART = 'CLEAN_CART';
export const ADD_TO_CART_FROM_SERVER = 'ADD_TO_CART_FROM_SERVER';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const PAGINATED_PRODUCTS = 'PAGINATED_PRODUCTS';
export const FILTER_PRODUCTS_STATUS = 'FILTER_PRODUCTS_STATUS';

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const GET_USER = "GET_USER";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const LOGOUT = "LOGOUT";